runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /api/.*
  script: api.src.main.app
- url: /assets
  static_dir: build/web/dist/assets
- url: /.*
  static_files: build/web/dist/app.html
  upload: build/web/dist/app.html